project_id = "jvwwynlzmyiwhyjcneck"

[functions.setup-admin]
verify_jwt = false

[functions.setup-guides]
verify_jwt = false

[functions.create-guide]
verify_jwt = true

[functions.get-whatsapp-groups]
verify_jwt = false

[functions.send-daily-poll]
verify_jwt = false

[functions.log-to-n8n]
verify_jwt = true

[functions.log-to-sheets]
verify_jwt = true

[functions.send-email-webhook]
verify_jwt = true
